[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hand_cricket = "BKY8UwwdM4cT5AUzJTL1yPUMcnPMpJy9BLk1g9ACcZMC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
